const DEFAULT_DATA={
 title:"دوامتان زرقاوتان",english:"BORUTO -TWO BLUE VORTEX-",japanese:"BORUTO -TWO BLUE VORTEX-",
 status:"مستمرة (مانجا شهرية)",author:"Masashi Kishimoto",artist:"Mikio Ikemoto",
 genres:["أكشن","مغامرات","شونين","قوة خارقة","دراما","خيال علمي"],
 description:"بعد أن تم تعديل ذكريات الجميع، يجد بوروتو نفسه مطارداً من قريته. وبعد هروبه مع ساسكي، ما المستقبل الذي ينتظر بوروتو...؟",
 cover:"assets/cover.png",chapters:[]
};
const STORE_KEY="vortex.reading";
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function readHistory(){try{return JSON.parse(localStorage.getItem(STORE_KEY)||"{}")}catch{return {}}}
function saveHistory(h){localStorage.setItem(STORE_KEY,JSON.stringify(h))}
function publicUrl(path){if(!path)return "";return `${window.SITE_CONFIG.SUPABASE_URL}/storage/v1/object/public/manga-pages/${String(path).split("/").filter(Boolean).map(encodeURIComponent).join("/")}`}
function chapterNumber(v){const n=Number(v);return Number.isInteger(n)&&n>0?n:null}
function formatDate(v){if(!v)return "";const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat("ar-IQ",{year:"numeric",month:"short",day:"numeric"}).format(d)}
async function getSupabase(){const cfg=window.SITE_CONFIG||{};if(!cfg.SUPABASE_URL||!cfg.SUPABASE_ANON_KEY)return null;if(window.__vortexSB)return window.__vortexSB;const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";await new Promise((ok,fail)=>{s.onload=ok;s.onerror=fail;document.head.appendChild(s)});window.__vortexSB=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);return window.__vortexSB}
async function loadData(){
 const local=(()=>{try{return {...DEFAULT_DATA,...JSON.parse(localStorage.getItem("mangaData")||"{}")}}catch{return DEFAULT_DATA}})();
 try{const sb=await getSupabase();if(!sb)return local;const m=await sb.from("manga").select("*").limit(1).maybeSingle();if(m.error||!m.data)return local;let c=await sb.from("chapters").select("id,number,title,published_at,pages(page_number,storage_path)").eq("manga_id",m.data.id).order("number",{ascending:false});if(c.error)c=await sb.from("chapters").select("id,number,title,published_at").eq("manga_id",m.data.id).order("number",{ascending:false});if(c.error)throw c.error;return {...DEFAULT_DATA,...m.data,cover:m.data.cover_url||local.cover||"assets/cover.png",chapters:(c.data||[]).map(x=>({...x,number:Number(x.number),date:x.published_at,pages:x.pages||[]}))};}catch(e){console.error(e);return local}}
function chapterImage(c,d){const first=(c.pages||[]).slice().sort((a,b)=>Number(a.page_number)-Number(b.page_number))[0];return first?.storage_path?publicUrl(first.storage_path):(c.cover_url||c.thumbnail_url||d.cover||"assets/cover.png")}
function progressFor(n){const h=readHistory()[String(n)];return h?Math.max(0,Math.min(100,Number(h.percent)||0)):0}
function renderContinue(d){const box=document.getElementById("continueCard"),wrap=document.getElementById("continue"),h=readHistory();const nums=Object.keys(h).map(Number).filter(Number.isFinite).sort((a,b)=>(h[String(b)].updatedAt||0)-(h[String(a)].updatedAt||0));const n=nums.find(x=>d.chapters.some(c=>Number(c.number)===x));if(!n){wrap.classList.remove("has-items");return}const c=d.chapters.find(x=>Number(x.number)===n),p=h[String(n)]||{};box.innerHTML=`<div class="continue-card"><img class="continue-cover" src="${esc(chapterImage(c,d))}" alt=""><div><div class="kicker">LAST READ</div><h3>الفصل ${n} — ${esc(c.title||"")}</h3><div style="color:#77868d;font-size:12px">${Math.round(p.percent||0)}% مكتمل · صفحة ${Number(p.page||1)}</div><div class="progress-track"><i style="width:${Math.round(p.percent||0)}%"></i></div></div><a class="resume-btn" href="reader.html?chapter=${n}&resume=1">متابعة القراءة ←</a></div>`;wrap.classList.add("has-items")}
function renderChapters(d){const grid=document.getElementById("chapterGrid");if(!grid)return;const q=(document.getElementById("search")?.value||"").trim().toLowerCase(),sort=document.getElementById("sort")?.value||"desc",h=readHistory();let ch=(d.chapters||[]).filter(c=>chapterNumber(c.number)!==null).filter(c=>`${c.number} ${c.title||""}`.toLowerCase().includes(q));ch.sort((a,b)=>{const diff=chapterNumber(a.number)-chapterNumber(b.number);return sort==="desc"?-diff:diff});if(!ch.length){grid.innerHTML='<div class="empty">لا توجد فصول مطابقة لبحثك.</div>';return}grid.innerHTML=ch.map((c,i)=>{const n=chapterNumber(c.number),p=progressFor(n),read=p>=99;return `<a class="chapter-card ${read?'read':''}" href="reader.html?chapter=${n}"><div class="chapter-cover"><img src="${esc(chapterImage(c,d))}" alt="غلاف الفصل ${n}" loading="lazy"><span class="chapter-badge">${i===0?'الأحدث':'الفصل '+n}</span><span class="read-badge">مقروء</span></div><div class="chapter-body"><div class="num">CHAPTER ${String(n).padStart(2,'0')}</div><h3>${esc(c.title||'الفصل '+n)}</h3><div class="chapter-meta"><span>${esc(formatDate(c.date))}</span><span>${p>0&&p<99?Math.round(p)+'%':''}</span></div><div class="chapter-progress"><i style="width:${p}%"></i></div></div></a>`}).join("")}
async function render(){const d=await loadData();for(const k of ["title","english","description","author","artist","status"]){const el=document.getElementById(k);if(el)el.textContent=d[k]||""}const cover=document.getElementById("mangaCover");if(cover){cover.src=d.cover||"assets/cover.png";cover.onerror=()=>{cover.src="assets/cover.png"}}const genres=(d.genres||[]).map(g=>`<span class="chip">${esc(g)}</span>`).join("");const g=document.getElementById("genres"),ag=document.getElementById("aboutGenres");if(g)g.innerHTML=genres;if(ag)ag.innerHTML=genres;const count=document.getElementById("chapterCount");if(count)count.textContent=(d.chapters||[]).length;renderContinue(d);renderChapters(d)}
document.getElementById("search")?.addEventListener("input",()=>loadData().then(renderChapters));document.getElementById("sort")?.addEventListener("change",()=>loadData().then(renderChapters));render();
